### PR TITLE
Gradlify

### PR DESCRIPTION
**Pull request by andy-berry-dev**
Adding a simple Gradle build so people don't need to add this to Eclipse to get it to work. The only prerequisite is BladeRunner in the right place, gradle will be automagically downloaded.

### CODE REVIEW

**Comment by leggetter** [comment]
@andyberry88 Any chance of getting a README update to tell people how to do the basics with Gradle please?

I tried `./gradlew` and I get an error `Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain`.

This is probably related to your comment:

> The only prerequisite is BladeRunner in the right place, gradle will be automagically downloaded.

What is "the right place"? Can a check be added for this and a friendly error message be returned:
1. Identifying the problem
2. Stating how to resolve the problem

Note: I tried updating `build.gradle` to fix the BladeRunner sdk path but I still seem to get this. We should assume that users have little/no knowledge and provide all the info possible to reduce barriers to entry. My README assumed that devs would just use this as reference and generally be working from the tutorial. This was obviously an incorrect assumption so the README should be updated accordingly with some "Getting Started" / "How to Build" details.

**Comment by andy-berry-dev** [comment]
@leggetter I'll try and take a look at this sometime this week.

**Comment by andy-berry-dev** [comment]
@leggetter give it a go now.
BladeRunner needs to be in the root of the project now. It fails to compile, but thats because of changes that have gone into BRJS.

**Comment by leggetter** [comment]
@andy-berry-dev LOL

**Comment by andy-berry-dev** [comment]
> @andy-berry-dev LOL

There's only so long you can wait for your PR to be merged 😉

**Comment by sospirited** [comment]
Pretty sure I tested this 👍

**Comment by thecapdan** [comment]
Unsubscribe ;)

**Pull request closed without merging**
